lexik_jwt_authentication:
    token_ttl: '%env(resolve:JWT_TOKEN_TTL)%'
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
